collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 1
color:
  saturation: 0.8319011
  brandStrength: 0
  lightness: 0.7524167
  brandColors:
    - '#0D0D0B'
    - '#FFFFFF'
    - '#776F5C'
    - '#B3BCD0'
    - '#FAC890'
  rhythmicContrast: 0.6557465
layout_spectrum: 0.002779143
name: Wall street
