collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.3830507
  lightness: 0.6019961
  brandStrength: 1
  brandColors:
    - '#060605'
    - '#5D5242'
    - '#A29887'
    - '#FFFFFF'
    - '#91532F'
  rhythmicContrast: 0.4114529
typography_spectrum: 0.8353483
layout_spectrum: 0.002779143
name: Wall street
